n =input('Digite algo')
print(' {} é um Caracter?'.format(n), n.isalpha())
print('{} é um Número? ' .format(n), n.isnumeric())
print('{} é alfanumérico?' .format(n) , n.isalnum())
print('{} é tudo Maiúsculo?'.format(n) , n.isupper())
print('{} É tudo Minúsculo?'.format(n) , n.islower())
print('{} É somente espaços?'.format(n), n.isspace())
print('{} É um Número Real?'.format(n) , n.isdecimal())
print('{} Está Capitalizada?' .format(n) , n.istitle())